name: Build and Test Shimakaze.Tools.Csf/Serialization/Json

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/Shimakaze.Tools.Csf.Serialization.Json.yml"
      - "src/Shimakaze.Tools.Csf/Serialization/Json/**"
      - "test/Shimakaze.Tools.Csf/Serialization/Json/**"
      - "global.json"
      - "nuget.config"
      
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/Shimakaze.Tools.Csf.Serialization.Json.yml"
      - "src/Shimakaze.Tools.Csf/Serialization/Json/**"
      - "test/Shimakaze.Tools.Csf/Serialization/Json/**"
      - "global.json"
      - "nuget.config"

env:
  NUGET_TOKEN: ${{ secrets.NUGETKEY }}
  NUGET_USER: ${{ secrets.NUGET_USER }}
      
jobs:

  build-csf-Serialization-Json:
    name: Build Shimakaze.Tools.Csf/Serialization/Json
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Set Nuget Token
      run: dotnet nuget update source ShimakazeProject -u "$NUGET_USER" -p "$NUGET_TOKEN"
        
    - name: Restore dependencies
      run: dotnet restore ./src/Shimakaze.Tools.Csf/Serialization/Json
      
    - name: Build Shimakaze.Tools.Csf
      run: dotnet build --no-restore ./src/Shimakaze.Tools.Csf/Serialization/Json -c Release
      
    - uses: actions/upload-artifact@v2
      name: Upload Shimakaze.Tools.Csf to Artifacts
      with:
        name: Shimakaze.Tools.Csf
        path: ./src/Shimakaze.Tools.Csf/Serialization/Json/bin/Release

  test-linux-csf-Serialization-Json:
    name: Test Shimakaze.Tools.Csf/Serialization/Json on GNU/Linux Operating System
    needs: build-csf-Serialization-Json
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Set Nuget Token
      run: dotnet nuget update source ShimakazeProject -u "$NUGET_USER" -p "$NUGET_TOKEN"
        
    - name: Test
      run: dotnet test -l "console;verbosity=detailed" ./test/Shimakaze.Tools.Csf/Serialization/Json -c Release

  test-windows-csf-Serialization-Json:
    name: Test Shimakaze.Tools.Csf/Serialization/Json on Windows Operating System
    needs: build-csf-Serialization-Json
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Set Nuget Token
      run: dotnet nuget update source ShimakazeProject -u "$NUGET_USER" -p "$NUGET_TOKEN"
        
    - name: Test
      run: dotnet test -l "console;verbosity=detailed" ./test/Shimakaze.Tools.Csf/Serialization/Json -c Release
